### ISSUE TITLE
API_ENDPOINT and IS_OFFLINE not unset on deploy

### ISSUE THREAD

**Issue by cyberwombat** [arabold/serverless-export-env#14]
It think it's great that these vars are set but when I deploy live the plugin should run again and not have these set. If I run sls offline then deploy it pushes my env file with these vars so its not super useful at that point.

**Comment by herebebogans** [comment]
Exclude your .env file from the deployment with serverless.yml package excludes.

**Comment by cyberwombat** [comment]
Ya its what I ended up doing. Thanks.
