### ISSUE TITLE
is this project dead

### ISSUE THREAD

**Issue by xgiovio** [arabold/serverless-export-env#18]
Hello,
are developments on this project on halt?

**Comment by chkrause** [comment]
I am also interested in this topic, especially when the last changes will be made available as npm package. With the new changes a path could finally be included.

**Comment by arabold** [comment]
I have just published v1.3.0 which adds:
- Support different output file name and path. Thanks to [philiiiiiipp](https://github.com/philiiiiiipp).
- Export `Outputs` as environment variables. Thanks to [lielran](https://github.com/lielran).

I'm happy to add previous contributes as editors for the project to speed up future releases. As I'm currently not using `serverless-export-env` in my own projects (I'm not working with `serverless` at all right now), the personal need for keeping it up to date isn't as big as it used to be.)
