### ISSUE TITLE
Environment Variables under functions not showing 

### ISSUE THREAD

**Issue by willa75** [arabold/serverless-export-env#36]
Hello there,

I am currently using `serverless@2.5.2` and `serverless-export-env@2.0.0`. I am currently trying to export the environment variables used in a function (two dynamodb tables) with `sls export-env --all`, however, it still doesn't grab the environment variables under my functions. Would you be able to tell me how to resolve this issue?

**Comment by AXSJ** [comment]
I'm having the same issue

**Comment by willa75** [comment]
@AXSJ I believe there is a flag you need to set on the more recent versions to overwrite the existing .env file. In the older version it did this automatically, but I was able to get it working later on
