### ISSUE TITLE
CRLF new lines on Linux

### ISSUE THREAD

**Issue by OliverGavin** [arabold/serverless-export-env#7]
My .env seems to contain CRLF which is messing things up for me.

Is there any reason to have these on a Linux machine?

**Comment by arabold** [comment]
There's no specific reason other than CRLF in my experience works best if you use both Windows and Linux/Mac systems. When using a module like `dotenv` it shouldn't actually matter which kind of line breaks you're using. 

Having that said, if you want to create a pull request that automatically chooses the "right" one depending on the currently used platform, I'm happy to merge it.

**Comment by wheresrhys** [comment]
It does matter when exporting to .env then using a shell script to read .env into variables. I've found this workaround `serverless export-env --stage dev; tr -d "\r" < .env > .env-unix;`.

If you can point me to an appropriate place in your codebase to sniff line ending type I'll submit a PR

**Comment by arabold** [comment]
I've released a version 1.2.0 which uses the platform specific newline characters. So it should be `\n` for POSIX, `\r\n` for Windows. Let me know if that helps 👍
