### ISSUE TITLE
ignore envs

### ISSUE THREAD

**Issue by salsa2k** [arabold/serverless-export-env#9]
It is possible have something to ignore some envs and just create the one that I choose?

**Comment by arabold** [comment]
Not at the moment. What would be a use case for this?

**Comment by barnc** [comment]
I'd also like this feature - in terms of use case - i'm currently exporting the api gateway url to an env file for my front-end to pick up, and I don't want the other env vars i'm using polluting my .env file, as it's a .env file for a web app.

@arabold not sure if this project is still active, but let me know if this is something you think you might accept a PR for?

**Comment by arabold** [comment]
@barnc , thanks for explaining your scenario. Adding command line parameters to the `export-env` command would be preferable in this case, as this seems more of a special case that a general one. So, I wouldn't add settings for this to the `serverless.yaml` itself, only to the command line. Would that work for you?

I'm not sure when I'm getting to add this myself (probably closer to the end of the year), but I'm happy to accept any PRs.
